ignore:
	- "app/Console/"
	- "app/Exceptions/Handlers/"
	- "app/Http/Controllers/Auth/"
	- "app/Exceptions/ComposerNotAvailableException"
	- "app/Exceptions/ExecNotAvailableException"
	- "app/Exceptions/GitNotAvailableException"
	- "app/Exceptions/GitNotExecutableException"
	- "app/Exceptions/NoOnlineUpdateException"
	- "app/Exceptions/NotMasterException"
	- "app/Http/Middleware/LoginCheck"
	- "app/Http/Middleware/VerifyCsrfToken"
	- "app/Http/Middleware/RedirectIfAuthenticated"
	- "app/Providers/BroadcastServiceProvider"
